### ISSUE TITLE
Administrator Detection Faulty

### ISSUE THREAD

**Issue by ndo360** [K4CZP3R/P2PLauncher#12]
Greetings!

It appears that when you run the program as admin within a directory that has spaces, it will error out and say that it needs to be ran as admin to function. This bug in and of itself seems inconsistent, so I will keep my eyes out for it. I wrote a similar directory example that the users has, but changed the name for privacy reasons.

Directory Example: "C:\Users\Test Mc. Gee\Downloads\P2P-Launcher"

My presumption is that the 'Period' in the name throws the program's detection off, but I am unsure. The program does still load, but the error pops up.

**Comment by K4CZP3R** [comment]
Hmmm it should not have any effect in admin mode detection, but I will take a look at it!

**Comment by K4CZP3R** [comment]
Tested it with directories like:
`C:\Users\Kacper\Desktop\testwith. and spaces dot`
`C:\Users\Kacper\Desktop\testwith.dot`

Admin detection works flawlessly. 

Closing it for now, can be reopened when specific criteria to trigger it are found.
