### ISSUE TITLE
Public Address Preference Issue

### ISSUE THREAD

**Issue by ndo360** [K4CZP3R/P2PLauncher#13]
Greetings!

I found a bug where some people's programs are defaulting you their IPv6 Public Address. Is there a way to have the program detect their IPv4 address when possible?

An example was a client using the program got an IPv6 Public Address, which isn't supported in the program, but when they visited [ipchicken](https://ipchicken.com)they received their IPv4 Public Address.

Hopefully there can be a way to detect the IPv4 Public Address over the IPv6 when possible.

**Comment by K4CZP3R** [comment]
I will try to fix it!

**Comment by K4CZP3R** [comment]
Merged with dev. Available in the next dev release.
